In [25]:
import numpy as np

import torch
import torch.nn as nn
import torch.functional as F

from torch import optim

import pandas as pd

class My_Linear(nn.Module):
    def __init__(self, in_features, out_features, bias=True, device=None, name=None):
        super(My_Linear, self).__init__()
        self.Linear = nn.Linear(in_features, out_features, bias, device)
        self.name = name
    
    def forward(self, x):
        # print(f"My_Linear - X.shape: {x.shape}, name: {self.name}")
        x = self.Linear(x)
        return x

In [6]:
df = pd.read_csv('data/geolife/Data/000/csv/000.csv')
df.head(1)
df_test = df.iloc[:, :-2].copy()
df_test.head(1)

latitude   longitude  what  altitude          days
0  39.984702  116.318417     0       492  39744.120185

In [22]:
def get_device():
    if torch.cuda.is_available():
        device = torch.device('cuda:0')
    else:
        device = torch.device('cpu')
    return device

def df_to_tensor(df):
    device = get_device()
    return torch.from_numpy(df.values).float().to(device)

In [30]:
from sklearn.model_selection import train_test_split

train_set, test_set = train_test_split(df_test, train_size=0.7, random_state=123)

X = ['latitude', 'longitude', 'altitude', 'days']
y = ['latitude', 'longitude']

row = 10
train_set = train_set.iloc[:row, :].copy()

train_X = df_to_tensor(train_set[X])
train_y = df_to_tensor(train_set[y])

model = My_Linear(4, 2)
loss_fn = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)
out_list = []
loss_train = 0.0
epochs = 10
for epoch in range(epochs):
    for input in train_X:
        outputs = model(input)
        print(outputs)
        loss = loss_fn(outputs, train_y)
        loss.backward()
        optimizer.step()
        loss_train += loss.item()
    
    print(f"epoch:{epoch}, loss:{loss_train}")

tensor([ 14446.9902, -13492.7773], grad_fn=<AddBackward0>)
tensor([10405.8428, -9481.2021], grad_fn=<AddBackward0>)
tensor([ 6450.4893, -5513.5981], grad_fn=<AddBackward0>)
tensor([ 2502.3975, -1559.0204], grad_fn=<AddBackward0>)
tensor([-1504.5669,  2443.5837], grad_fn=<AddBackward0>)
tensor([-5533.4468,  6466.4849], grad_fn=<AddBackward0>)
tensor([-9534.4453, 10453.9717], grad_fn=<AddBackward0>)
tensor([-13421.3389,  14243.4980], grad_fn=<AddBackward0>)
tensor([-17012.7188,  17553.1680], grad_fn=<AddBackward0>)
tensor([-19572.9922,  19616.6016], grad_fn=<AddBackward0>)
epoch:0, loss:1346087930.0
tensor([-20963.5742,  20274.4062], grad_fn=<AddBackward0>)
tensor([-20957.9863,  19576.0664], grad_fn=<AddBackward0>)
tensor([-19623.0820,  17774.0215], grad_fn=<AddBackward0>)
tensor([-17550.9297,  15358.5293], grad_fn=<AddBackward0>)
tensor([-14911.8809,  12458.4883], grad_fn=<AddBackward0>)
tensor([-11804.6426,   9166.7256], grad_fn=<AddBackward0>)
tensor([-8373.7852,  5608.7310], grad_fn=

/home/shkoma/anaconda3/lib/python3.11/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([10, 2])) that is different to the input size (torch.Size([2])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [29]:
train_y

tensor([[ 31.1155, 121.0488],
        [ 40.0045, 116.3137],
        [ 39.9892, 116.2729],
        [ 40.0039, 116.3243],
        [ 40.1208, 116.2123],
        [ 39.9370, 116.3205],
        [ 39.8730, 116.4328],
        [ 39.9940, 116.3268],
        [ 39.9919, 116.3317],
        [ 39.9084, 116.3674]])